apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: bootstrap
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: root-ca-cert
  namespace: cert-manager
spec:
  isCA: true
  commonName: Root CA
  secretName: root-ca-cert-tls
  privateKey:
    algorithm: ECDSA
    size: 256
  issuerRef:
    name: bootstrap
    kind: ClusterIssuer
    group: cert-manager.io
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: root-ca
spec:
  ca:
    secretName: root-ca-cert-tls
