---
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: test1
  region: ap-southeast-1
  version: "1.27"
  tags:
    yb_owner: yrampuria
    yb_dept: sales
    yb_env: demo
    yb_task: demo
    yb_project: test1


vpc:
  id: vpc-05774065d62dde4a3
  subnets:
    private:
      ap-southeast-1a:
        id: subnet-00f009abb49c26a38

      ap-southeast-1b:
        id: subnet-0e5cf53d1949cf124

      ap-southeast-1c:
        id: subnet-07af89e6bc1dece0a

addons:
  - name: aws-ebs-csi-driver
    version: latest
    wellKnownPolicies:
      ebsCSIController: true
  - name: coredns
    version: latest
  - name: kube-proxy
    version: latest
  - name: vpc-cni
    attachPolicyARNs:
    - arn:aws:iam::aws:policy/AmazonEKS_CNI_Policy

managedNodeGroups:
  - name: test1-wkr-1
    availabilityZones:
    - ap-southeast-1a
    instanceType: m7a.2xlarge
    minSize: 0
    maxSize: 3
    desiredCapacity: 1
    volumeSize: 100
    privateNetworking: true
    spot: true
    ssh:
      enableSSM: true
      publicKeyName: yrpoc
    securityGroups:
      attachIDs:
      - sg-093d7932a3c9af9a0
    labels:
      roles: worker
    tags:
      nodegroup-role: worker
      yb_owner: yrampuria
      yb_dept: sales
      yb_task: demo
      yb_env: demo
      yb_project: test1
    # iam:
    #   withAddonPolicies:
    #     autoScaler: true
    #     externalDNS: true
    #     certManager: true
    #     ebs: true
    #     efs: true
    #     awsLoadBalancerController: true
    #     cloudWatch: true
  - name: test1-wkr-2
    availabilityZones:
    - ap-southeast-1b
    instanceType: m7a.2xlarge
    minSize: 0
    maxSize: 3
    desiredCapacity: 1
    volumeSize: 100
    privateNetworking: true
    spot: true
    ssh:
      enableSSM: true
      publicKeyName: yrpoc
    securityGroups:
      attachIDs:
      - sg-093d7932a3c9af9a0
    labels:
      roles: worker
    tags:
      nodegroup-role: worker
      yb_owner: yrampuria
      yb_dept: sales
      yb_task: demo
      yb_env: demo
      yb_project: test1
    # iam:
    #   withAddonPolicies:
    #     autoScaler: true
    #     externalDNS: true
    #     certManager: true
    #     ebs: true
    #     efs: true
    #     awsLoadBalancerController: true
    #     cloudWatch: true
  - name: test1-wkr-3
    availabilityZones:
    - ap-southeast-1c
    instanceType: m7a.2xlarge
    minSize: 0
    maxSize: 3
    desiredCapacity: 1
    volumeSize: 100
    privateNetworking: true
    spot: true
    ssh:
      enableSSM: true
      publicKeyName: yrpoc
    securityGroups:
      attachIDs:
      - sg-093d7932a3c9af9a0
    labels:
      roles: worker
    tags:
      nodegroup-role: worker
      yb_owner: yrampuria
      yb_dept: sales
      yb_task: demo
      yb_env: demo
      yb_project: test1
    # iam:
    #   withAddonPolicies:
    #     autoScaler: true
    #     externalDNS: true
    #     certManager: true
    #     ebs: true
    #     efs: true
    #     awsLoadBalancerController: true
    #     cloudWatch: true
