apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: root-ca
  name: yba
spec:
  tls:
  - hosts:
      - $YBA_HOSTNAME
      - $YBA_PROM_HOSTNAME
    secretName: yba-tls
  ingressClassName: nginx
  rules:
  - host: $YBA_HOSTNAME
    http:
      paths:
      - backend:
          service:
            name: yba-yugaware-ui
            port:
              number: 80
        path: /
        pathType: Prefix
  - host: $YBA_PROM_HOSTNAME
    http:
      paths:
      - backend:
          service:
            name: yba-yugaware-ui
            port:
              number: 9090
        path: /
        pathType: Prefix
